name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate metrics svg
        uses: lowlighter/metrics@v3.34
        with:
          template: classic
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          plugin_followup: yes
          plugin_followup_indepth: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
